[tool.poetry]
name = "harlequin-wherobots"
version = "0.1.0"
description = ""
authors = ["Maxime Petazzoni <maxime.petazzoni@bulix.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
